/**
 * @file MenuPrincipal.java
 */
package src.CapaPresentacio;

/** @class MenuPrincipal
 *  @brief Vista del menu principal
 *
 *  @author alvaro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private CtrlPresentacio cp;
    private javax.swing.JFrame parent;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(javax.swing.JFrame parent, CtrlPresentacio cp) {
        super("Menu");
        this.cp = cp;
        this.parent = parent;
        initComponents();
        nomUser.setText(cp.getNomUser());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        botoNewGame = new javax.swing.JButton();
        botoLoadGame = new javax.swing.JButton();
        botoRankingGlobal = new javax.swing.JButton();
        botoLogOut = new javax.swing.JButton();
        botoGameRanking = new javax.swing.JButton();
        botoQuit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nomUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kakuro");
        setMinimumSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        menu.setName(""); // NOI18N

        botoNewGame.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        botoNewGame.setText("NEW GAME");
        botoNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoNewGameActionPerformed(evt);
            }
        });

        botoLoadGame.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        botoLoadGame.setText("LOAD GAME");
        botoLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoLoadGameActionPerformed(evt);
            }
        });

        botoRankingGlobal.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        botoRankingGlobal.setText("GLOBAL RANKING");
        botoRankingGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoRankingGlobalActionPerformed(evt);
            }
        });

        botoLogOut.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        botoLogOut.setText("LOG OUT");
        botoLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoLogOutActionPerformed(evt);
            }
        });

        botoGameRanking.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        botoGameRanking.setText("GAME RANKING");
        botoGameRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoGameRankingActionPerformed(evt);
            }
        });

        botoQuit.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        botoQuit.setText("QUIT");
        botoQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoQuitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        jLabel1.setText("User:");

        nomUser.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(370, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botoLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botoLoadGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botoNewGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botoGameRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botoQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botoRankingGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(369, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomUser)
                .addContainerGap(756, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(botoNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botoLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botoRankingGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botoGameRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botoLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botoQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomUser))
                .addGap(89, 89, 89))
        );

        getContentPane().add(menu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botoQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botoQuitActionPerformed

    private void botoGameRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoGameRankingActionPerformed
        boolean[] tipus = new boolean[]{false, false, true};
        VistaSeleccioKakuro partida = new VistaSeleccioKakuro(this,cp, tipus);
        partida.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botoGameRankingActionPerformed

    private void botoLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoLogOutActionPerformed
        parent.setVisible(true);
        dispose();
    }//GEN-LAST:event_botoLogOutActionPerformed

    private void botoRankingGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoRankingGlobalActionPerformed
        VistaRankingGlobal ranking = new VistaRankingGlobal(this,cp);
        ranking.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botoRankingGlobalActionPerformed

    private void botoLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoLoadGameActionPerformed
        boolean[] tipus = new boolean[]{false, true, false};
        VistaSeleccioKakuro partida = new VistaSeleccioKakuro(this,cp, tipus);
        partida.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botoLoadGameActionPerformed

    private void botoNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoNewGameActionPerformed
        VistaNewGame partida = new VistaNewGame(this,cp);
        partida.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botoNewGameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoGameRanking;
    private javax.swing.JButton botoLoadGame;
    private javax.swing.JButton botoLogOut;
    private javax.swing.JButton botoNewGame;
    private javax.swing.JButton botoQuit;
    private javax.swing.JButton botoRankingGlobal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel nomUser;
    // End of variables declaration//GEN-END:variables
}
