/**
 * @file PantallaPrincipal.java
 */
package src.CapaPresentacio;

import java.awt.Color;
import java.util.HashSet;

/** @class PantallaPrincipal
 *  @brief Vista de la pantalla principal/inicial del programa
 *
 *  @author alvaro
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    private CtrlPresentacio cp;
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal(CtrlPresentacio cp) {
        this.cp = cp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        botoSignUp = new javax.swing.JButton();
        botoLogIn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        missatge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kakuro");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jLabel1.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("User:");

        user.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userKeyPressed(evt);
            }
        });

        pass.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passMouseClicked(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password:");

        botoSignUp.setFont(new java.awt.Font("Chandas", 0, 12)); // NOI18N
        botoSignUp.setText("SignUp");
        botoSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botoSignUp.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        botoSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoSignUpActionPerformed(evt);
            }
        });

        botoLogIn.setFont(new java.awt.Font("Chandas", 0, 12)); // NOI18N
        botoLogIn.setText("LogIn");
        botoLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botoLogIn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        botoLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoLogInMouseClicked(evt);
            }
        });
        botoLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoLogInActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extras/Imatges/kakuroInici.jpg"))); // NOI18N
        jLabel7.setText("jLabel4");

        missatge.setForeground(new java.awt.Color(235, 95, 95));

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginLayout.createSequentialGroup()
                                .addComponent(botoSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botoLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(missatge))))
                .addGap(33, 33, 33))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botoLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(missatge)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(login);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void botoSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoSignUpActionPerformed
        SignUp signin = new SignUp(this,cp);
        signin.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_botoSignUpActionPerformed

    private void botoLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoLogInActionPerformed
        String u = user.getText();
        String psw = new String (pass.getPassword());
        
        if (u.isBlank()) {
            user.setBackground(new Color(234, 95, 95));
            pass.setBackground(new Color(234, 95, 95));
            user.setText("");
            pass.setText("");
            missatge.setText("*User incorrect*");
        
        }
        else if (!cp.existeixUsuari(u)) {
            user.setBackground(new Color(234, 95, 95));
            pass.setBackground(new Color(234, 95, 95));
            user.setText("");
            pass.setText("");
            missatge.setText("*User not exists*");
        }
        
        else if (cp.comprovaUsuari(u, psw)) {
            missatge.setText("");
            MenuPrincipal menu = new MenuPrincipal(this,cp);
            menu.setVisible(true);
            this.setVisible(false);
        }
        
        else {
            user.setBackground(new Color(234, 95, 95));
            pass.setBackground(new Color(234, 95, 95));
            pass.setText("");
            missatge.setText("*Password incorrect*");
        }    
    }//GEN-LAST:event_botoLogInActionPerformed

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        user.setEditable(true);
        user.setBackground(Color.white);
        pass.setBackground(Color.white);
    }//GEN-LAST:event_userMouseClicked

    private void passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseClicked
        pass.setBackground(Color.white);
    }//GEN-LAST:event_passMouseClicked

    private void botoLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoLogInMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botoLogInMouseClicked

    private void userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyPressed
        char c = evt.getKeyChar();
        if (c == ' ') {
            user.setEditable(false);
        }
        else user.setEditable(true);
    }//GEN-LAST:event_userKeyPressed

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        char c = evt.getKeyChar();
        if (c == ' ') {
            pass.setEditable(false);
        }
        else pass.setEditable(true);
    }//GEN-LAST:event_passKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoLogIn;
    private javax.swing.JButton botoSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel login;
    private javax.swing.JLabel missatge;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
