/**
 * @file SignUp.java
 */
package src.CapaPresentacio;

import java.awt.Color;

/** @class SignUp   
 *  @brief Vista de la pantalla de signup/enregistrament d'usuaris
 *
 *  @author alvaro
 */
public class SignUp extends javax.swing.JFrame {
    
    private CtrlPresentacio cp;
    private javax.swing.JFrame parent;
    /**
     * Creates new form SignIn
     */
    public SignUp(javax.swing.JFrame parent, CtrlPresentacio cp) {
        this.cp = cp;
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        confirm = new javax.swing.JPasswordField();
        botosignup = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        botoreturn = new javax.swing.JButton();
        missatge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kakuro");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        jLabel1.setText("User:");

        jLabel2.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        jLabel2.setText("Password:");

        jLabel3.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        jLabel3.setText("Confirm Password:");

        user.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userKeyPressed(evt);
            }
        });

        pass.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passMouseClicked(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
        });

        confirm.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
        });
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        confirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmKeyPressed(evt);
            }
        });

        botosignup.setFont(new java.awt.Font("Chandas", 0, 12)); // NOI18N
        botosignup.setText("SignUp");
        botosignup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botosignup.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        botosignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botosignupActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extras/Imatges/kakuroInici.jpg"))); // NOI18N
        jLabel7.setText("jLabel4");

        botoreturn.setFont(new java.awt.Font("Chandas", 0, 12)); // NOI18N
        botoreturn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botoreturn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        botoreturn.setLabel("Return");
        botoreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoreturnActionPerformed(evt);
            }
        });

        missatge.setFont(new java.awt.Font("Chandas", 0, 12)); // NOI18N
        missatge.setForeground(new java.awt.Color(234, 95, 95));
        missatge.setText("                                 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(confirm)
                                    .addComponent(user)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(botoreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botosignup, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(missatge)
                        .addGap(111, 111, 111))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botosignup, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botoreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(missatge)
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmActionPerformed

    private void botosignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botosignupActionPerformed
        String u = user.getText();
        String psw = new String (pass.getPassword());
        String cfrm = new String (confirm.getPassword());
        
        if (u.isBlank()) {
            user.setBackground(new Color(234, 95, 95));
            pass.setBackground(new Color(234, 95, 95));
            confirm.setBackground(new Color(234, 95, 95));
            user.setText("");
            pass.setText("");
            confirm.setText("");
            missatge.setText("*User incorrect*");
        
        }
        else if (cp.existeixUsuari(u)) {
            user.setBackground(new Color(234, 95, 95));
            pass.setBackground(new Color(234, 95, 95));
            confirm.setBackground(new Color(234, 95, 95));
            user.setText("");
            pass.setText("");
            confirm.setText("");
            missatge.setText("*User already exists*");
        }
        
        else if (psw.equals(cfrm)) {
            missatge.setText("");
            cp.signUp(u, psw);
            MenuPrincipal menu = new MenuPrincipal(parent,cp);
            menu.setVisible(true);
            dispose();
        }
        
        else {
            user.setBackground(new Color(234, 95, 95));
            pass.setBackground(new Color(234, 95, 95));
            confirm.setBackground(new Color(234, 95, 95));
            user.setText("");
            pass.setText("");
            confirm.setText("");
            missatge.setText("*Password not match*");
        }
    }//GEN-LAST:event_botosignupActionPerformed

    private void botoreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoreturnActionPerformed
        parent.setVisible(true);
        dispose();
    }//GEN-LAST:event_botoreturnActionPerformed

    private void confirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmKeyPressed
        char c = evt.getKeyChar();
        if (c == ' ') {
            confirm.setEditable(false);
        }
        else confirm.setEditable(true);
    }//GEN-LAST:event_confirmKeyPressed

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        char c = evt.getKeyChar();
        if (c == ' ') {
            pass.setEditable(false);
        }
        else pass.setEditable(true);
    }//GEN-LAST:event_passKeyPressed

    private void userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyPressed
        char c = evt.getKeyChar();
        if (c == ' ') {
            user.setEditable(false);
        }
        else user.setEditable(true);
    }//GEN-LAST:event_userKeyPressed

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        user.setEditable(true);
        user.setBackground(Color.white);
        pass.setBackground(Color.white);
        confirm.setBackground(Color.white);
    }//GEN-LAST:event_userMouseClicked

    private void passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseClicked
        pass.setBackground(Color.white);
        confirm.setBackground(Color.white);
    }//GEN-LAST:event_passMouseClicked

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseClicked
        pass.setBackground(Color.white);
        confirm.setBackground(Color.white);
    }//GEN-LAST:event_confirmMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoreturn;
    private javax.swing.JButton botosignup;
    private javax.swing.JPasswordField confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel missatge;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
