/**
 * @file VistaAutogenerar.java
 */
package src.CapaPresentacio;

/** @class VistaAutogenerar
 *  @brief Vista de la pantalla per generar kakuros amb paràmetres
 *
 *  @author ignasi
 */
public class VistaAutogenerar extends javax.swing.JFrame {
    
    javax.swing.JFrame parent;
    CtrlPresentacio cp;
    /**
     * Creates new form VistaAutogenerar
     */
    public VistaAutogenerar() {
        cp = new CtrlPresentacio();
        initComponents();
    }

        
    public VistaAutogenerar(javax.swing.JFrame parent, CtrlPresentacio cp) {
        this.parent = parent;
        this.cp = cp;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelTextRows = new javax.swing.JLabel();
        LabelTextColumns = new javax.swing.JLabel();
        LabelTextDifficulty = new javax.swing.JLabel();
        BotoEasy = new javax.swing.JRadioButton();
        BotoMedium = new javax.swing.JRadioButton();
        BotoHard = new javax.swing.JRadioButton();
        SliderRows = new javax.swing.JSlider();
        SliderColumns = new javax.swing.JSlider();
        BotoOK = new javax.swing.JButton();
        BotoReturn = new javax.swing.JButton();
        LabelRows = new javax.swing.JLabel();
        LabelColumns = new javax.swing.JLabel();
        LabelTitol = new javax.swing.JLabel();
        LabelAvis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 900));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 700));

        LabelTextRows.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        LabelTextRows.setText("Choose the number of rows.");

        LabelTextColumns.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        LabelTextColumns.setText("Choose the number of columns.");

        LabelTextDifficulty.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        LabelTextDifficulty.setText("Choose your difficulty.");

        BotoEasy.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        BotoEasy.setText("Easy");
        BotoEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoEasyActionPerformed(evt);
            }
        });

        BotoMedium.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        BotoMedium.setText("Medium");
        BotoMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoMediumActionPerformed(evt);
            }
        });

        BotoHard.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        BotoHard.setText("Hard");
        BotoHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoHardActionPerformed(evt);
            }
        });

        SliderRows.setMaximum(17);
        SliderRows.setMinimum(3);
        SliderRows.setValue(10);
        SliderRows.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderRowsStateChanged(evt);
            }
        });

        SliderColumns.setMaximum(17);
        SliderColumns.setMinimum(3);
        SliderColumns.setValue(10);
        SliderColumns.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderColumnsStateChanged(evt);
            }
        });

        BotoOK.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        BotoOK.setText("OK");
        BotoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoOKActionPerformed(evt);
            }
        });

        BotoReturn.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        BotoReturn.setText("Return Menu");
        BotoReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoReturnActionPerformed(evt);
            }
        });

        LabelRows.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        LabelRows.setText("10");

        LabelColumns.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        LabelColumns.setText("10");

        LabelTitol.setFont(new java.awt.Font("Chandas", 0, 18)); // NOI18N
        LabelTitol.setText("Autogenerate Kakuro");

        LabelAvis.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        LabelAvis.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotoReturn)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LabelTextDifficulty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelTextColumns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelTextRows, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(127, 127, 127)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BotoHard, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BotoMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(LabelColumns)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SliderColumns, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(LabelRows)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SliderRows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(BotoOK, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BotoEasy, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(142, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelAvis)
                        .addGap(226, 226, 226))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelTitol, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(LabelTitol)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelTextRows, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelRows)
                        .addComponent(SliderRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelTextColumns)
                        .addComponent(LabelColumns))
                    .addComponent(SliderColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(BotoEasy)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(BotoHard)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotoReturn)
                            .addComponent(BotoOK)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotoMedium)
                        .addComponent(LabelTextDifficulty)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(LabelAvis)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotoReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoReturnActionPerformed
        parent.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotoReturnActionPerformed

    private void BotoOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoOKActionPerformed
        int nFiles = SliderRows.getValue();
        int nColumnes = SliderColumns.getValue();
        String dif = "";
        boolean difTriada = true;
        if (BotoEasy.isSelected()){dif = "facil";}
        else if (BotoMedium.isSelected()){dif = "mig";}
        else if (BotoHard.isSelected()){dif = "dificil";}
        else {difTriada = false; LabelAvis.setText("Please choose a difficulty");}

        if (difTriada){
            
            cp.generarIGuardarRandomKakuro(dif,nFiles,nColumnes);
            VistaPartida VP = new VistaPartida(this,cp);
            VP.setVisible(true);
            this.setVisible(false);
              
            
        }
    }//GEN-LAST:event_BotoOKActionPerformed

    private void SliderColumnsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderColumnsStateChanged
        LabelColumns.setText(String.valueOf(SliderColumns.getValue()));
    }//GEN-LAST:event_SliderColumnsStateChanged

    private void SliderRowsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderRowsStateChanged
        LabelRows.setText(String.valueOf(SliderRows.getValue()));
    }//GEN-LAST:event_SliderRowsStateChanged

    private void BotoHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoHardActionPerformed
        if (BotoHard.isSelected()){
            BotoEasy.setSelected(false);
            BotoMedium.setSelected(false);
        }
    }//GEN-LAST:event_BotoHardActionPerformed

    private void BotoMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoMediumActionPerformed
        if (BotoMedium.isSelected()){
            BotoEasy.setSelected(false);
            BotoHard.setSelected(false);
        }
    }//GEN-LAST:event_BotoMediumActionPerformed

    private void BotoEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoEasyActionPerformed
        if (BotoEasy.isSelected()){
            BotoMedium.setSelected(false);
            BotoHard.setSelected(false);
        }
    }//GEN-LAST:event_BotoEasyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotoEasy;
    private javax.swing.JRadioButton BotoHard;
    private javax.swing.JRadioButton BotoMedium;
    private javax.swing.JButton BotoOK;
    private javax.swing.JButton BotoReturn;
    private javax.swing.JLabel LabelAvis;
    private javax.swing.JLabel LabelColumns;
    private javax.swing.JLabel LabelRows;
    private javax.swing.JLabel LabelTextColumns;
    private javax.swing.JLabel LabelTextDifficulty;
    private javax.swing.JLabel LabelTextRows;
    private javax.swing.JLabel LabelTitol;
    private javax.swing.JSlider SliderColumns;
    private javax.swing.JSlider SliderRows;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
