/**
 * @file VistaNewGame.java
 */
package src.CapaPresentacio;

/** @class VistaNewGame
 *  @brief Vista per començar una partida nova (per seleccionar el mètode per generar-la)
 *
 *  @author alvaro
 */
public class VistaNewGame extends javax.swing.JFrame {
    
    private CtrlPresentacio cp;
    private javax.swing.JFrame parent;
    /**
     * Creates new form VistaNewGame
     */
    public VistaNewGame(javax.swing.JFrame parent, CtrlPresentacio cp) {
        this.cp = cp;
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botomanual = new javax.swing.JButton();
        botocarregar = new javax.swing.JButton();
        botoautogenerar = new javax.swing.JButton();
        botoreturn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        botomanual.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        botomanual.setText("CREATE MANUALLY");
        botomanual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botomanualActionPerformed(evt);
            }
        });

        botocarregar.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        botocarregar.setText("LOAD FROM REPOSITORY");
        botocarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botocarregarActionPerformed(evt);
            }
        });

        botoautogenerar.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        botoautogenerar.setText("AUTOGENERATE");
        botoautogenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoautogenerarActionPerformed(evt);
            }
        });

        botoreturn.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        botoreturn.setText("Return Menu");
        botoreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoreturnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        jLabel1.setText("SELECT HOW YOU WANT TO GENERATE THE NEW GAME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botoreturn)
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botocarregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botomanual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botoautogenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(339, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addComponent(botomanual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botocarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botoautogenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(botoreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botomanualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botomanualActionPerformed
        VistaCrearManualment manual = new VistaCrearManualment(this,cp);
        manual.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botomanualActionPerformed

    private void botocarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botocarregarActionPerformed
        boolean[] tipus = new boolean[]{true, false, false};
        VistaSeleccioKakuro partida = new VistaSeleccioKakuro(parent,cp, tipus);
        partida.setVisible(true);
        dispose();
    }//GEN-LAST:event_botocarregarActionPerformed

    private void botoautogenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoautogenerarActionPerformed
        VistaAutogenerar auto = new VistaAutogenerar(this,cp);
        auto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botoautogenerarActionPerformed

    private void botoreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoreturnActionPerformed
        parent.setVisible(true);
        dispose();
    }//GEN-LAST:event_botoreturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoautogenerar;
    private javax.swing.JButton botocarregar;
    private javax.swing.JButton botomanual;
    private javax.swing.JButton botoreturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
