/**
 * @file VistaSeleccioKakuro.java
 */
package src.CapaPresentacio;

import javax.swing.DefaultListModel;

/** @class VistaSeleccioKakuro
 *  @brief Vista per seleccionar una partida/taulell guardats
 *
 *  @author alvaro
 */
public class VistaSeleccioKakuro extends javax.swing.JFrame {

    private CtrlPresentacio cp;
    private javax.swing.JFrame parent;
    private String[] facils;
    private boolean facil;
    private String[] mitjans;
    private boolean mig;
    private String[] dificils;
    private boolean dificil;
    private boolean[] tipus; //{NEW GAME, LOAD GAME, RANKING KAKURO}
    private String user;
    /**
     * Creates new form VistaSeleccioKakuro
     */
    public VistaSeleccioKakuro(javax.swing.JFrame parent, CtrlPresentacio cp, boolean[] tipus) {
        this.cp = cp;
        this.parent = parent;
        this.tipus = tipus;
        initComponents();
        user = cp.getNomUser();
        if(!tipus[1]) {
            this.facils = cp.getKakuroFacilTots();
            this.mitjans = cp.getKakuroMigTots();
            this.dificils = cp.getKakuroDificilTots();
        }
        
        else {
            this.facils = cp.getKakuroFacilUser(user);
            this.mitjans = cp.getKakuroMigUser(user);
            this.dificils = cp.getKakuroDificilUser(user);
        }
        
        facil = mig = dificil = true;
        actualitzarLlista();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        llista = new javax.swing.JList<>();
        botofacil = new javax.swing.JRadioButton();
        botomig = new javax.swing.JRadioButton();
        botodificil = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        botoNext = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botoreturn = new javax.swing.JButton();
        missatge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        llista.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        llista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(llista);

        botofacil.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        botofacil.setSelected(true);
        botofacil.setText("Easy Kakuro");
        botofacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botofacilActionPerformed(evt);
            }
        });

        botomig.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        botomig.setSelected(true);
        botomig.setText("Medium Kakuro");
        botomig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botomigActionPerformed(evt);
            }
        });

        botodificil.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        botodificil.setSelected(true);
        botodificil.setText("Hard Kakuro");
        botodificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botodificilActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        jLabel1.setText("Select one kakuro from the list");

        botoNext.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        botoNext.setText("Next");
        botoNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoNextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        jLabel2.setText("Filter by difficulty");

        botoreturn.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        botoreturn.setText("Return Menu");
        botoreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoreturnActionPerformed(evt);
            }
        });

        missatge.setFont(new java.awt.Font("Chandas", 0, 12)); // NOI18N
        missatge.setForeground(new java.awt.Color(234, 95, 95));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botoreturn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(missatge, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botoNext, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botomig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botofacil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botodificil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoNext, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botoreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(missatge, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botofacil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botomig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botodificil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void cleanList(){
        DefaultListModel model = new DefaultListModel();
        llista.setModel(model);
        
    }
    
    private void addData(){
        DefaultListModel model = (DefaultListModel) llista.getModel();
        
        if (facil) {
            for (int i = 0; i < facils.length; i++) { model.addElement(facils[i]);}
        }
            
        if (mig) {
            for (int i = 0; i < mitjans.length; i++) { model.addElement(mitjans[i]);}
        }
            
        if (dificil) {
            for (int i = 0; i < dificils.length; i++) { model.addElement(dificils[i]);}
        }
        
    }
    
    private void actualitzarLlista(){
        cleanList();
        addData();        
    }
    
    private void botofacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botofacilActionPerformed
        facil = !facil;
        actualitzarLlista();
    }//GEN-LAST:event_botofacilActionPerformed

    private void botomigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botomigActionPerformed
        mig = !mig;
        actualitzarLlista();
    }//GEN-LAST:event_botomigActionPerformed

    private void botodificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botodificilActionPerformed
        dificil = !dificil;
        actualitzarLlista();
    }//GEN-LAST:event_botodificilActionPerformed

    private void botoreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoreturnActionPerformed
        parent.setVisible(true);
        dispose();
    }//GEN-LAST:event_botoreturnActionPerformed

    private void botoNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoNextActionPerformed
        if(!llista.isSelectionEmpty()) {
            System.out.println(llista.getSelectedValue());
            if (!tipus[2]){
                if (tipus[0]){
                cp.carregarKakuro(llista.getSelectedValue());
                VistaPartida partida = new VistaPartida(parent, cp);
                partida.setVisible(true);
                dispose();
                }
                
                else{
                cp.carregarPartida(llista.getSelectedValue());
                VistaPartida partida = new VistaPartida(parent, cp);
                partida.setVisible(true);
                dispose();
                }
            }
            
            else {
                VistaRankingPartida ranking = new VistaRankingPartida(parent,cp, llista.getSelectedValue());
                ranking.setVisible(true);
                dispose();
            }
        }
        
        else {
            missatge.setText("*You have to select a Kakuro*");
        }
    }//GEN-LAST:event_botoNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoNext;
    private javax.swing.JRadioButton botodificil;
    private javax.swing.JRadioButton botofacil;
    private javax.swing.JRadioButton botomig;
    private javax.swing.JButton botoreturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> llista;
    private javax.swing.JLabel missatge;
    // End of variables declaration//GEN-END:variables
}
