/**
 * @file VistaCrearManualment.java
 */
package src.CapaPresentacio;

/** @class VistaCrearManualment
 *  @brief Vista de la pantalla per crear manualment (a ma) un kakuro
 *
 *  @author ignasi
 */
public class VistaCrearManualment extends javax.swing.JFrame {

    private CtrlPresentacio cp;
    private javax.swing.JFrame parent;
    
    /**
     * Creates new form VistaCrearManualment
     */
    public VistaCrearManualment(javax.swing.JFrame parent, CtrlPresentacio cp) {
        this.cp = cp;
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelcolumnes = new javax.swing.JLabel();
        labelfiles = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sliderColumns = new javax.swing.JSlider();
        sliderRow = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        textkakuro = new javax.swing.JTextArea();
        play = new javax.swing.JButton();
        returnmenu = new javax.swing.JButton();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jLabel2.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        jLabel2.setText("Create Kakuro manually");

        labelcolumnes.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        labelcolumnes.setText("Number of columns: 10");

        labelfiles.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        labelfiles.setText("Number of rows: 10");

        jLabel4.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        jLabel4.setText("Type the kakuro:");

        sliderColumns.setMaximum(17);
        sliderColumns.setMinimum(3);
        sliderColumns.setValue(10);
        sliderColumns.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderColumnsStateChanged(evt);
            }
        });

        sliderRow.setMaximum(17);
        sliderRow.setMinimum(3);
        sliderRow.setValue(10);
        sliderRow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRowStateChanged(evt);
            }
        });

        textkakuro.setColumns(20);
        textkakuro.setRows(5);
        jScrollPane1.setViewportView(textkakuro);

        play.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        play.setText("Validate and play");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        returnmenu.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        returnmenu.setText("Return Menu");
        returnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnmenuActionPerformed(evt);
            }
        });

        error.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        error.setForeground(new java.awt.Color(234, 95, 95));
        error.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(returnmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(play)
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelcolumnes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelfiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sliderColumns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sliderRow, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sliderRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sliderColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelcolumnes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error))
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sliderColumnsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderColumnsStateChanged
        labelcolumnes.setText("Number of columns: " + String.valueOf(sliderColumns.getValue()));
        
    }//GEN-LAST:event_sliderColumnsStateChanged

    private void sliderRowStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRowStateChanged
        labelfiles.setText("Number of rows: " + String.valueOf(sliderRow.getValue()));
    }//GEN-LAST:event_sliderRowStateChanged

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        String taulell = textkakuro.getText();

        boolean correcte = cp.newTaulell(taulell, sliderRow.getValue(), sliderColumns.getValue());
       

        if(correcte) {
            VistaPartida VP = new VistaPartida(parent,cp);
            VP.setVisible(true);
            this.setVisible(false);
        } 
        else {
            error.setText("*Incorrect Kakuro*");
        }
    }//GEN-LAST:event_playActionPerformed

    private void returnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnmenuActionPerformed
        parent.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnmenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelcolumnes;
    private javax.swing.JLabel labelfiles;
    private javax.swing.JButton play;
    private javax.swing.JButton returnmenu;
    private javax.swing.JSlider sliderColumns;
    private javax.swing.JSlider sliderRow;
    private javax.swing.JTextArea textkakuro;
    // End of variables declaration//GEN-END:variables
}
