/**
 * @file VistaRankingGlobal.java
 */
package src.CapaPresentacio;

import java.util.AbstractMap;
import java.util.ArrayList;


/** @class VistaRankingGlobal
 *  @brief Vista per consultar el ranking global
 *
 * º@author alvaro
 */
public class VistaRankingGlobal extends javax.swing.JFrame {
    
    private CtrlPresentacio cp;
    private javax.swing.JFrame parent;
    
    /**
     * Creates new form VistaRankingGlobal
     */
    public VistaRankingGlobal(javax.swing.JFrame parent, CtrlPresentacio cp) {
        this.cp = cp;
        this.parent = parent;  
        initComponents();
        String user = cp.getNomUser();
        nomUser.setText(user);
        punts.setText(String.valueOf(cp.getPuntuacioGlobal(user)));
        setRanking();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        nomUser = new javax.swing.JLabel();
        punts = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ranking = new javax.swing.JLabel();
        user2 = new javax.swing.JLabel();
        user3 = new javax.swing.JLabel();
        user4 = new javax.swing.JLabel();
        user5 = new javax.swing.JLabel();
        points1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        points2 = new javax.swing.JLabel();
        points3 = new javax.swing.JLabel();
        points4 = new javax.swing.JLabel();
        points5 = new javax.swing.JLabel();
        position1 = new javax.swing.JLabel();
        position2 = new javax.swing.JLabel();
        position3 = new javax.swing.JLabel();
        position4 = new javax.swing.JLabel();
        position5 = new javax.swing.JLabel();
        sortir = new javax.swing.JButton();
        nomuser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        menu.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        jLabel1.setText("User:");

        label9.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        label9.setText("Points:");

        nomUser.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N

        punts.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        punts.setText("0");

        jLabel4.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Position");

        jLabel5.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Points");

        ranking.setFont(new java.awt.Font("Chandas", 1, 20)); // NOI18N
        ranking.setText("RANKING GLOBAL");

        user2.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        user2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user2.setText("- - -");

        user3.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        user3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user3.setText("- - -");

        user4.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        user4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user4.setText("- - -");

        user5.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        user5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user5.setText("- - -");

        points1.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        points1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        points1.setText("- - -");

        jLabel6.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("User");

        user1.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        user1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user1.setText("- - -");

        points2.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        points2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        points2.setText("- - -");

        points3.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        points3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        points3.setText("- - -");

        points4.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        points4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        points4.setText("- - -");

        points5.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        points5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        points5.setText("- - -");

        position1.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        position1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        position1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extras/Imatges/gold.png"))); // NOI18N

        position2.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        position2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        position2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extras/Imatges/silver.png"))); // NOI18N

        position3.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        position3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        position3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extras/Imatges/bronze.png"))); // NOI18N

        position4.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        position4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        position4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extras/Imatges/fourth.png"))); // NOI18N

        position5.setFont(new java.awt.Font("Chandas", 1, 15)); // NOI18N
        position5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        position5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extras/Imatges/fifth.png"))); // NOI18N

        sortir.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N
        sortir.setText("Return Menu");
        sortir.setPreferredSize(new java.awt.Dimension(115, 39));
        sortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortirActionPerformed(evt);
            }
        });

        nomuser.setFont(new java.awt.Font("Chandas", 0, 15)); // NOI18N

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(punts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(nomUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nomuser, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(399, 399, 399)))
                .addComponent(sortir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(position4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(position3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(position2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(position1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(position5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(points1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(points2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(points3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(points4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(points5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(250, 250, 250))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ranking)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(ranking)
                .addGap(18, 18, 18)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(position1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(position2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(points1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(points2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(points3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(position3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(points4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(position4, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(points5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(position5, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomuser, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(nomUser)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label9)
                            .addComponent(punts))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sortir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );

        getContentPane().add(menu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortirActionPerformed
        parent.setVisible(true);
        dispose();
    }//GEN-LAST:event_sortirActionPerformed

    private void setRanking() {
        String[][] ranking = cp.rankingUsuaris();
        
        for (int i = 0; i < ranking.length; i++) {
            if (i == 0) {
                user1.setText(ranking[i][0]);
                points1.setText(ranking[i][1]);
                
            }
            
            else if (i == 1) {
                user2.setText(ranking[i][0]);
                points2.setText(ranking[i][1]);
                
            }
            
            else if (i == 2) {
                user3.setText(ranking[i][0]);
                points3.setText(ranking[i][1]);
                
            }
            
            else if (i == 3) {
                user4.setText(ranking[i][0]);
                points4.setText(ranking[i][1]);
                
            }
            
            else if (i == 4) {
                user5.setText(ranking[i][0]);
                points5.setText(ranking[i][1]);
                
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label9;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel nomUser;
    private javax.swing.JLabel nomuser;
    private javax.swing.JLabel points1;
    private javax.swing.JLabel points2;
    private javax.swing.JLabel points3;
    private javax.swing.JLabel points4;
    private javax.swing.JLabel points5;
    private javax.swing.JLabel position1;
    private javax.swing.JLabel position2;
    private javax.swing.JLabel position3;
    private javax.swing.JLabel position4;
    private javax.swing.JLabel position5;
    private javax.swing.JLabel punts;
    private javax.swing.JLabel ranking;
    private javax.swing.JButton sortir;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel user2;
    private javax.swing.JLabel user3;
    private javax.swing.JLabel user4;
    private javax.swing.JLabel user5;
    // End of variables declaration//GEN-END:variables
}
